#!/usr/bin/env python
"""Stack existing RVT outputs into the 3-band input the Chactun model expects.

The individual visualisations were already generated by RVT with the project's
own parameters, so nothing needs reimplementing -- SVF, positive openness and
slope only need combining, in that order, and putting on the value scale the
model was trained with.

Band order is Chactun's: sky-view factor, positive openness, slope. It is not
interchangeable; the pretrained first layer learned what each channel carries.

Each band is linearly mapped so its valid pixels take Chactun's own mean and
standard deviation. RVT's byte stretch and Somrak's need not agree, and matching
the statistics puts the input where the model expects it regardless.
"""
import argparse
import os

import numpy as np
import rasterio

CHACTUN_MEAN = [216.527, 198.453, 228.612]
CHACTUN_SD = [26.915, 16.698, 21.212]
NAMES = ["sky-view factor", "positive openness", "slope"]


def read_band(path):
    with rasterio.open(path) as s:
        a = s.read(1).astype(np.float32)
        nod = s.nodata
        prof = s.profile
        v = np.isfinite(a)
        if nod is not None:
            v &= a != nod
        return a, v, prof, s.crs, s.transform


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--svf", required=True)
    p.add_argument("--opos", required=True)
    p.add_argument("--slope", required=True)
    p.add_argument("--out", required=True)
    a = p.parse_args()

    bands, valids = [], []
    crs = tr = None
    for path, name in ((a.svf, NAMES[0]), (a.opos, NAMES[1]), (a.slope, NAMES[2])):
        arr, v, prof, c, t = read_band(path)
        print("%-20s %s  %dx%d  dtype %s  nodata %s"
              % (name, os.path.basename(path), arr.shape[1], arr.shape[0],
                 prof["dtype"], prof.get("nodata")))
        bands.append(arr)
        valids.append(v)
        crs, tr = c, t

    shapes = {b.shape for b in bands}
    if len(shapes) != 1:
        raise SystemExit("band shapes differ: %s" % shapes)

    valid = valids[0] & valids[1] & valids[2]
    # RVT writes real nodata; also drop the all-zero border the tiles carry
    valid &= ~((bands[0] == 0) & (bands[1] == 0) & (bands[2] == 0))
    print()
    print("valid pixels: %.1f%%" % (100 * valid.mean()))

    h, w = bands[0].shape
    out = np.zeros((3, h, w), np.uint8)
    print()
    print("%-20s %12s %10s %12s %10s"
          % ("band", "raw mean", "raw sd", "-> mean", "-> sd"))
    for i in range(3):
        v = bands[i][valid]
        sd = v.std()
        if sd < 1e-9:
            sd = 1.0
        z = (bands[i] - v.mean()) / sd
        scaled = z * CHACTUN_SD[i] + CHACTUN_MEAN[i]
        scaled[~valid] = 0
        out[i] = np.clip(scaled, 0, 255).astype(np.uint8)
        vv = out[i][valid]
        print("%-20s %12.3f %10.3f %12.1f %10.1f"
              % (NAMES[i], v.mean(), v.std(), vv.mean(), vv.std()))

    prof = {"driver": "GTiff", "height": h, "width": w, "count": 3,
            "dtype": "uint8", "crs": crs, "transform": tr,
            "compress": "deflate", "photometric": "RGB", "tiled": True}
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    with rasterio.open(a.out, "w", **prof) as dst:
        dst.write(out)
        dst.update_tags(bands="svf,positive_openness,slope",
                        stretch="linear to Chactun per-band mean/sd",
                        source_svf=os.path.basename(a.svf),
                        source_opos=os.path.basename(a.opos),
                        source_slope=os.path.basename(a.slope))
    print()
    print("wrote %s" % a.out)


if __name__ == "__main__":
    main()
